CREATE TABLE IF NOT EXISTS vm_groups (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    config_json TEXT NOT NULL,
    replicas INTEGER NOT NULL CHECK (replicas >= 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE vms ADD COLUMN group_id INTEGER REFERENCES vm_groups(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_vms_group_id ON vms(group_id);
