name: build-kernel

on:
  workflow_dispatch:
    inputs:
      ch_linux_commit:
        description: 'Cloud Hypervisor Linux commit SHA'
        required: true
  push:
    tags:
      - 'kernel-v*'

permissions:
  contents: write
  id-token: write
  attestations: write # Required for actions/attest-build-provenance

env:
  GO_VERSION: "1.24.x"
  BUSYBOX_URL: "https://github.com/shutingrz/busybox-static-binaries-fat/raw/refs/heads/main/busybox-x86_64-linux-gnu"
  BUSYBOX_SHA256: "5c566ba50a12d8020a391346575534e818a1f5b6f729a53b7b241262fe1d1b4e"
  CH_LINUX_REPO: "https://github.com/cloud-hypervisor/linux.git"
  OUT_DIR: out
  ARCH: x86_64

jobs:
  build:
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ca-certificates curl git wget \
            build-essential bc bison flex libssl-dev libelf-dev dwarves \
            cpio xz-utils zstd gcc g++ make file pkg-config
          sudo update-ca-certificates

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build volary (deterministic)
        run: |
          export CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOWORK=off GOFLAGS="-trimpath"
          go build -buildvcs=false -ldflags "-s -w -buildid=" -o build/volary ./cmd/volary
          file build/volary

      - name: Build init (static, deterministic)
        run: |
          gcc -static -s -Wl,--build-id=none -o build/init build/init.c
          file build/init

      - name: Prepare deterministic initramfs (stage)
        run: |
          set -eu
          WORKDIR=/tmp/initramfs
          rm -rf "$WORKDIR"
          mkdir -p "$WORKDIR/bin" "$WORKDIR/sbin" "$WORKDIR/etc" "$WORKDIR/proc" "$WORKDIR/sys" "$WORKDIR/dev" "$WORKDIR/usr/bin" "$WORKDIR/usr/sbin"
          cp build/volary "$WORKDIR/bin/volary"
          cp build/init "$WORKDIR/init"
          chmod 0755 "$WORKDIR/init" "$WORKDIR/bin/volary"
          curl -fsSL "$BUSYBOX_URL" -o "$WORKDIR/bin/busybox"
          if [ -n "$BUSYBOX_SHA256" ]; then echo "$BUSYBOX_SHA256  $WORKDIR/bin/busybox" | sha256sum -c -; fi
          chmod +x "$WORKDIR/bin/busybox"
          "$WORKDIR/bin/busybox" --install -s "$WORKDIR/bin"

      - name: Clone Cloud Hypervisor Linux
        id: chlinux
        run: |
          set -eu
          COMMIT="${{ github.event.inputs.ch_linux_commit || '' }}"
          if [ -z "$COMMIT" ]; then
            echo "Provide ch_linux_commit when running workflow_dispatch or use a tag-driven run" >&2
            exit 1
          fi
          git clone --depth=1 "$CH_LINUX_REPO" linux
          git -C linux fetch --depth=1 origin "$COMMIT"
          git -C linux checkout "$COMMIT"
          TS=$(git -C linux show -s --format=%ct "$COMMIT")
          echo "ts=$TS" >> "$GITHUB_OUTPUT"
          echo "commit=$COMMIT" >> "$GITHUB_OUTPUT"

      - name: Bake deterministic initramfs
        run: |
          set -eu
          TS="${{ steps.chlinux.outputs.ts }}"
          WORKDIR=/tmp/initramfs
          export SOURCE_DATE_EPOCH="$TS"
          find "$WORKDIR" -exec touch -h -d @"$SOURCE_DATE_EPOCH" {} +
          ( cd "$WORKDIR" && find . -print0 | cpio --null -ov --format=newc | gzip -n -9 > "$GITHUB_WORKSPACE/build/volant-initramfs.cpio.gz" )

      - name: Configure kernel
        run: |
          set -eu
          cd linux
          make ch_defconfig
          scripts/config --set-str LOCALVERSION ""
          scripts/config --disable LOCALVERSION_AUTO
          scripts/config --enable INITRAMFS_SOURCE
          scripts/config --set-str INITRAMFS_SOURCE "$GITHUB_WORKSPACE/build/volant-initramfs.cpio.gz"
          scripts/config --enable INITRAMFS_COMPRESSION_GZIP
          scripts/config --enable DEBUG_INFO_NONE || true
          yes "" | make ARCH=${{ env.ARCH }} olddefconfig

      - name: Build kernel (bzImage)
        run: |
          set -eu
          cd linux
          export KBUILD_BUILD_USER=volant
          export KBUILD_BUILD_HOST=gh-actions
          export KBUILD_BUILD_TIMESTAMP="${{ steps.chlinux.outputs.ts }}"
          export SOURCE_DATE_EPOCH="$KBUILD_BUILD_TIMESTAMP"
          make ARCH=${{ env.ARCH }} -j"$(nproc)" bzImage
          mkdir -p "$GITHUB_WORKSPACE/${{ env.OUT_DIR }}/kernels/${{ env.ARCH }}"
          cp arch/x86/boot/bzImage "$GITHUB_WORKSPACE/${{ env.OUT_DIR }}/kernels/${{ env.ARCH }}/bzImage"

      - name: Checksums and metadata
        run: |
          set -eu
          cd ${{ env.OUT_DIR }}
          sha256sum kernels/${{ env.ARCH }}/bzImage | tee kernels/${{ env.ARCH }}/bzImage.sha256
          cp ../linux/.config kernels/${{ env.ARCH }}/kernel.config
          echo "${{ steps.chlinux.outputs.commit }}" > kernels/${{ env.ARCH }}/KERNEL_COMMIT

      - name: Generate build provenance
        uses: actions/attest-build-provenance@v3
        id: attest
        with:
          subject-path: |
            ${{ env.OUT_DIR }}/kernels/${{ env.ARCH }}/bzImage
            ${{ env.OUT_DIR }}/kernels/${{ env.ARCH }}/bzImage.sha256
            ${{ env.OUT_DIR }}/kernels/${{ env.ARCH }}/kernel.config
            ${{ env.OUT_DIR }}/kernels/${{ env.ARCH }}/KERNEL_COMMIT
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${{ env.ARCH }}
          path: |
            ${{ env.OUT_DIR }}/kernels/${{ env.ARCH }}/bzImage
            ${{ env.OUT_DIR }}/kernels/${{ env.ARCH }}/bzImage.sha256
            ${{ env.OUT_DIR }}/kernels/${{ env.ARCH }}/kernel.config
            ${{ env.OUT_DIR }}/kernels/${{ env.ARCH }}/KERNEL_COMMIT
            ${{ steps.attest.outputs.bundle-path }}

  release:
    needs: build
    runs-on: [self-hosted, ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: kernel-${{ env.ARCH }}
          path: out/release

      - name: Attach to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/release/bzImage
            out/release/bzImage.sha256
            out/release/kernel.config
            out/release/KERNEL_COMMIT
            out/release/*.intoto.jsonl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}